fileVersion: 1
id: "119"
mappingDefinitions:
  EMPTY:
    database: ""
    schema: ""
  ENV_PRESYNC:
    database: BEN_EDW
    schema: TRASH_ENV
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  WORK:
    database: BEN_EDW
    schema: TRASH_ENV
name: New Environment
type: Environment
